multiDb: true
migrationsDisabled: false

master:
  driver: postgres
  database: slot_games
  host: slot-games.postgres
  #  host: localhost
  user: postgres
  password: password
  port: 5432

slave:
  driver: postgres
  database: slot_games
  host: slot-games.postgres
  #  host: localhost
  user: postgres
  password: password
  port: 5432